"""test_post에 author 컬럼 추가

Revision ID: 2a5b19e1c850
Revises: d5ef7f1b4a52
Create Date: 2026-09-10 13:16:08.863960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel 이 만든 컬럼 타입(sqlmodel.sql.sqltypes.AutoString 등)이
# autogenerate 결과에 들어오므로, 마이그레이션 파일에서도 import 가 필요함
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a5b19e1c850'
down_revision: Union[str, Sequence[str], None] = 'd5ef7f1b4a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_post', sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('test_post', 'author', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_post', 'author')
    # ### end Alembic commands ###
