"""init: create test_post

Revision ID: d5ef7f1b4a52
Revises: 
Create Date: 2026-09-10 11:22:45.144740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel 이 만든 컬럼 타입(sqlmodel.sql.sqltypes.AutoString 등)이
# autogenerate 결과에 들어오므로, 마이그레이션 파일에서도 import 가 필요함
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5ef7f1b4a52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_post',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_post')
    # ### end Alembic commands ###
